
theme = "flatcheip"

[editor]
# Show currently open buffers, only when more than one exists.
bufferline = "multiple"
# Highlight all lines with a cursor
# cursorline = true
# Use relative line numbers
# line-number = "relative"
# Show a ruler at column 120
rulers = [120]
# Force the theme to show colors
true-color = true


[editor.gutters]
layout = ["diff", "diagnostics", "spacer"]


[keys.insert]
"Cmd-g" = "normal_mode"
